export type FaultCode =
  | "guard"
  | "rejected"
  | "configuration"
  | "process"
  | "timeout"
  | "aborted"
  | "workspace"
  | "conflict"
  | "prompt"
  | "response"
  | "session"
  | "provider"
  | "limit"
  | "quota"
  | "replay"
  | "steering";
