export const nativeRecipeTypes = [
  [
    "task.options",
    "RecipeTaskSettings",
    "application/recipes/workflow-components.types.ts",
    null,
    null,
    4,
  ],
  [
    "workflow.options",
    "RecipeWorkflowSettings",
    "application/recipes/workflow-components.types.ts",
    null,
    null,
    4,
  ],
  [
    "loop.options",
    "RecipeLoopSettings",
    "application/recipes/workflow-components.types.ts",
    null,
    null,
    4,
  ],
  [
    "decisionTask.options",
    "RecipeDecisionSettings",
    "application/recipes/workflow-components.types.ts",
    null,
    null,
    4,
  ],
  [
    "isolated.options",
    "RecipeIsolatedSettings",
    "application/recipes/workflow-components.types.ts",
    null,
    null,
    4,
  ],
  [
    "call.options",
    "RecipeCallSettings",
    "application/recipes/workflow-components.types.ts",
    null,
    null,
    4,
  ],

  [
    "steering.controller",
    "RecipeEmptyOptions",
    "application/recipes/agent-components.types.ts",
    "createSteering",
    "domain/steering.ts",
    3,
  ],
  [
    "harness.outpost",
    "HarnessOptions",
    "domain/harness.types.ts",
    "createHarness",
    "domain/harness.ts",
    3,
  ],
  [
    "modelProvider.openai",
    "OpenAIModelProviderOptions",
    "adapters/models/openai-model-provider.types.ts",
    "createOpenAIModelProvider",
    "adapters/models/openai-model-provider.ts",
    3,
  ],
  [
    "modelProvider.anthropic",
    "AnthropicModelProviderOptions",
    "adapters/models/anthropic-model-provider.types.ts",
    "createAnthropicModelProvider",
    "adapters/models/anthropic-model-provider.ts",
    3,
  ],
  [
    "decisionProvider.system-one",
    "SystemOneDecisionProviderOptions",
    "adapters/decisions/system-one-provider.types.ts",
    "createSystemOneDecisionProvider",
    "adapters/decisions/system-one-provider.ts",
    3,
  ],
  [
    "tool.custom",
    "HarnessToolOptions",
    "domain/tool.types.ts",
    "defineHarnessTool",
    "domain/tool.ts",
    3,
  ],
  [
    "tool.subagent",
    "HarnessSubagentOptions",
    "domain/subagent.types.ts",
    "defineHarnessSubagent",
    "domain/subagent.ts",
    3,
  ],
  [
    "toolset.custom",
    "HarnessToolsetOptions",
    "domain/tool.types.ts",
    "defineHarnessToolset",
    "domain/tool.ts",
    3,
  ],
  [
    "toolset.files",
    "RecipeEmptyOptions",
    "application/recipes/agent-components.types.ts",
    "createHarnessFileTools",
    "adapters/tools/file-tools.ts",
    3,
  ],
  [
    "toolset.edit",
    "RecipeEmptyOptions",
    "application/recipes/agent-components.types.ts",
    "createHarnessEditTools",
    "adapters/tools/edit-tools.ts",
    3,
  ],
  [
    "toolset.git",
    "RecipeEmptyOptions",
    "application/recipes/agent-components.types.ts",
    "createHarnessGitTools",
    "adapters/tools/git-tools.ts",
    3,
  ],
  [
    "toolset.search",
    "RecipeEmptyOptions",
    "application/recipes/agent-components.types.ts",
    "createHarnessSearchTools",
    "adapters/tools/search-tools.ts",
    3,
  ],
  [
    "toolset.shell",
    "ShellToolsOptions",
    "adapters/tools/tools.types.ts",
    "createHarnessShellTools",
    "adapters/tools/shell-tools.ts",
    3,
  ],
  [
    "permissions.rules",
    "HarnessPermissionsOptions",
    "domain/permissions.types.ts",
    "defineHarnessPermissions",
    "domain/permissions.ts",
    3,
  ],
  [
    "hook.custom",
    "HarnessHookOptions",
    "domain/hook.types.ts",
    "defineHarnessHook",
    "domain/hook.ts",
    3,
  ],
  [
    "skill.custom",
    "HarnessSkillOptions",
    "domain/skill.types.ts",
    "defineHarnessSkill",
    "domain/skill.ts",
    3,
  ],
  [
    "context.custom",
    "HarnessContextStrategyOptions",
    "domain/context.types.ts",
    "defineHarnessContextStrategy",
    "domain/context.ts",
    3,
  ],
  [
    "context.truncate",
    "TruncateToolResultsOptions",
    "domain/context.types.ts",
    "truncateToolResults",
    "domain/context.ts",
    3,
  ],
  [
    "context.summarize",
    "SummarizeHistoryOptions",
    "domain/context.types.ts",
    "summarizeHistory",
    "domain/context.ts",
    3,
  ],
  [
    "instructions.source",
    "RecipeInstructionsOptions",
    "application/recipes/agent-components.types.ts",
    "defineRecipeInstructions",
    "application/recipes/agent-components.ts",
    3,
  ],
  [
    "instructions.mcp",
    "McpPromptOptions",
    "domain/mcp-prompt.types.ts",
    "defineMcpPrompt",
    "domain/mcp-prompt.ts",
    3,
  ],
  [
    "agent.fallback",
    "RecipeFallbackOptions",
    "application/recipes/agent-components.types.ts",
    "defineRecipeFallback",
    "application/recipes/agent-components.ts",
    3,
  ],
  [
    "agent.replay",
    "ReplayAgentOptions",
    "domain/replay.types.ts",
    "createReplayAgent",
    "domain/replay.ts",
    3,
  ],
  [
    "response.json",
    "RecipeJsonResponseOptions",
    "application/recipes/agent-components.types.ts",
    "defineRecipeJsonResponse",
    "application/recipes/agent-components.ts",
    3,
  ],
  [
    "response.text",
    "TextResponseOptions",
    "domain/response.types.ts",
    "defineTextResponse",
    "domain/response.ts",
    3,
  ],
  [
    "decision.questions",
    "DecisionOptions",
    "domain/decision.types.ts",
    "defineDecision",
    "domain/decision.ts",
    3,
  ],
  [
    "routing.decision",
    "RecipeRoutingOptions",
    "application/recipes/agent-components.types.ts",
    "defineHarnessModelRouting",
    "domain/harness-routing.ts",
    3,
  ],
  [
    "conversations.transport",
    "RecipeTransportConversationsOptions",
    "application/recipes/agent-components.types.ts",
    "createRecipeConversations",
    "application/recipes/agent-components.ts",
    3,
  ],
  [
    "conversations.harness",
    "RecipeEmptyOptions",
    "application/recipes/agent-components.types.ts",
    "createHarnessConversations",
    "infrastructure/conversations/harness-store.ts",
    3,
  ],
  [
    "conversations.claude",
    "RecipeEmptyOptions",
    "application/recipes/agent-components.types.ts",
    "createClaudeConversations",
    "adapters/agents/claude/claude-conversations.ts",
    3,
  ],
  [
    "conversations.codex",
    "RecipeEmptyOptions",
    "application/recipes/agent-components.types.ts",
    "createCodexConversations",
    "adapters/agents/codex/codex-conversations.ts",
    3,
  ],
  [
    "conversations.copilot",
    "RecipeEmptyOptions",
    "application/recipes/agent-components.types.ts",
    "createCopilotConversations",
    "adapters/agents/copilot/copilot-conversations.ts",
    3,
  ],
  [
    "conversations.kimi",
    "RecipeEmptyOptions",
    "application/recipes/agent-components.types.ts",
    "createKimiConversations",
    "adapters/agents/kimi/kimi-conversations.ts",
    3,
  ],
  [
    "conversations.transcript",
    "TranscriptConversationLayout",
    "infrastructure/conversations/layout.types.ts",
    "createTranscriptConversations",
    "infrastructure/conversations/transcript-store.ts",
    3,
  ],
  [
    "conversations.bundle",
    "SessionBundleProfile",
    "infrastructure/conversations/session-bundle.types.ts",
    "createSessionBundleConversations",
    "infrastructure/conversations/session-bundle.ts",
    3,
  ],
  [
    "dispatch.options",
    "RecipeDispatchSettings",
    "application/recipes/agent-components.types.ts",
    null,
    null,
    3,
  ],
  [
    "sandboxProvider.docker",
    "ContainerOptions",
    "providers/container.types.ts",
    "createDockerSandboxProvider",
    "providers/docker.ts",
    2,
  ],
  [
    "sandboxProvider.podman",
    "ContainerOptions",
    "providers/container.types.ts",
    "createPodmanSandboxProvider",
    "providers/podman.ts",
    2,
  ],
  [
    "sandboxProvider.local",
    "LocalOptions",
    "providers/local.types.ts",
    "createLocalSandboxProvider",
    "providers/local.ts",
    2,
  ],
  [
    "sandboxProvider.vercel",
    "VercelOptions",
    "providers/vercel.types.ts",
    "createVercelSandboxProvider",
    "providers/vercel.ts",
    2,
  ],
  [
    "sandboxProvider.daytona",
    "DaytonaOptions",
    "providers/daytona.types.ts",
    "createDaytonaSandboxProvider",
    "providers/daytona.ts",
    2,
  ],
  [
    "sandboxProvider.firecracker",
    "FirecrackerOptions",
    "providers/firecracker.types.ts",
    "createFirecrackerSandboxProvider",
    "providers/firecracker.ts",
    2,
  ],
  [
    "profile.portable",
    "AgentProfileOptions",
    "domain/agent-profile.types.ts",
    "defineAgentProfile",
    "domain/agent-profile.ts",
    2,
  ],
  [
    "secretSource.vault",
    "VaultSecretSourceOptions",
    "adapters/secrets/vault.types.ts",
    "createVaultSecretSource",
    "adapters/secrets/vault.ts",
    2,
  ],
  [
    "secretSource.aws",
    "AwsSecretSourceOptions",
    "adapters/secrets/aws.types.ts",
    "createAwsSecretSource",
    "adapters/secrets/aws.ts",
    2,
  ],
  [
    "secretSource.azure",
    "AzureSecretSourceOptions",
    "adapters/secrets/azure.types.ts",
    "createAzureSecretSource",
    "adapters/secrets/azure.ts",
    2,
  ],
  [
    "secretSource.gcp",
    "GcpSecretSourceOptions",
    "adapters/secrets/gcp.types.ts",
    "createGcpSecretSource",
    "adapters/secrets/gcp.ts",
    2,
  ],
  [
    "secretSource.onepassword",
    "OnePasswordSecretSourceOptions",
    "adapters/secrets/onepassword.types.ts",
    "createOnePasswordSecretSource",
    "adapters/secrets/onepassword.ts",
    2,
  ],
  [
    "secretSource.infisical",
    "InfisicalSecretSourceOptions",
    "adapters/secrets/infisical.types.ts",
    "createInfisicalSecretSource",
    "adapters/secrets/infisical.ts",
    2,
  ],
  [
    "sandbox.options",
    "SandboxOptions",
    "application/outpost.types.ts",
    null,
    null,
    2,
  ],
  [
    "harness.codex",
    "CodexSettings",
    "adapters/agents/settings.types.ts",
    "createCodexHarness",
    "adapters/agents/codex/codex-adapter.ts",
    2,
  ],
  [
    "harness.claude",
    "ClaudeSettings",
    "adapters/agents/settings.types.ts",
    "createClaudeHarness",
    "adapters/agents/claude/claude-adapter.ts",
    2,
  ],
  [
    "harness.agy",
    "AntigravitySettings",
    "adapters/agents/antigravity/antigravity.types.ts",
    "createAntigravityHarness",
    "adapters/agents/antigravity/antigravity-adapter.ts",
    2,
  ],
  [
    "harness.copilot",
    "CopilotSettings",
    "adapters/agents/copilot/copilot.types.ts",
    "createCopilotHarness",
    "adapters/agents/copilot/copilot-adapter.ts",
    2,
  ],
  [
    "harness.kimi",
    "KimiSettings",
    "adapters/agents/kimi/kimi.types.ts",
    "createKimiHarness",
    "adapters/agents/kimi/kimi-adapter.ts",
    2,
  ],
  [
    "agent.composed",
    "AgentOptions",
    "domain/agent.types.ts",
    "createAgent",
    "domain/agent.ts",
    2,
  ],
  [
    "transport.local",
    "LocalTransportOptions",
    "infrastructure/local-transport.types.ts",
    "createLocalTransport",
    "infrastructure/local-transport.ts",
    2,
  ],
] as const;

export const nativeRecipeKinds: Readonly<Record<string, string>> = {
  Agent: "agent",
  WorkflowCheckpointStore: "checkpointStore",
  TaskCache: "taskCache",
  WorkflowDecisionVerifier: "verifier",
  CliAgent: "agent",
  CustomAgent: "agent",
  DispatchAgent: "agent",
  SandboxProvider: "sandboxProvider",
  Sandbox: "sandbox",
  Workspace: "workspace",
  AgentProfile: "profile",
  ObservationHub: "observation",
  ObservationSink: "sink",
  CliHarness: "harness",
  Harness: "harness",
  ModelProvider: "modelProvider",
  ResponseSpec: "response",
  Decision: "decision",
  StandardValidator: "validator",
  StandardJsonSchema: "validator",
  Steering: "steering",
  DispatchTelemetry: "telemetry",
  DecisionProvider: "decisionProvider",
  HarnessInstructions: "instructions",
  HarnessTool: "tool",
  HarnessSubagent: "tool",
  HarnessToolset: "toolset",
  HarnessHook: "hook",
  HarnessSkill: "skill",
  HarnessPermissions: "permissions",
  HarnessContextStrategy: "context",
  ConversationStore: "conversations",
  HarnessModelRouting: "routing",
  SecretSource: "secretSource",
  Transport: "transport",
  AbortSignal: "signal",
  Readable: "object",
  Writable: "object",
};

export const nativeRecipePaths: Readonly<Record<string, readonly string[]>> = {
  "isolated.options": ["repository", "conversationHome", "brief.file"],
  "sandbox.options": ["repository", "conversationHome"],
  "sandboxProvider.docker": ["volumes.*.source"],
  "sandboxProvider.podman": ["volumes.*.source"],
  "sandboxProvider.firecracker": [
    "kernel",
    "rootfs",
    "ssh.identity",
    "ssh.knownHosts",
    "jailer.directory",
  ],
  "harness.codex": ["authentication.account.file"],
  "harness.claude": ["authentication.account.file"],
  "harness.agy": ["authentication.account.file"],
  "harness.copilot": ["authentication.account.file"],
  "harness.kimi": ["authentication.account.file"],
  "transport.local": ["directory"],
};

export const nativeRecipeSecrets: Readonly<Record<string, readonly string[]>> =
  {
    "secretSource.vault": ["token"],
    "modelProvider.openai": ["apiKey"],
    "modelProvider.anthropic": ["apiKey"],
    "decisionProvider.system-one": ["apiKey"],
    "sandboxProvider.daytona": ["connection.apiKey", "connection.jwtToken"],
    "sandboxProvider.vercel": [
      "create.token",
      "create.source.password",
      "create.source.username",
    ],
    "harness.codex": ["authentication.account.key", "authentication.usage.key"],
    "harness.claude": [
      "authentication.account.key",
      "authentication.usage.key",
    ],
    "harness.agy": ["authentication.account.key", "authentication.usage.key"],
    "harness.copilot": [
      "authentication.account.key",
      "authentication.usage.key",
    ],
    "harness.kimi": ["authentication.account.key", "authentication.usage.key"],
  };
