export const nativeRecipeTypes = [
  [
    "sandboxProvider.docker",
    "ContainerOptions",
    "providers/container.types.ts",
    "createDockerSandboxProvider",
    "providers/docker.ts",
    2,
  ],
  [
    "sandboxProvider.podman",
    "ContainerOptions",
    "providers/container.types.ts",
    "createPodmanSandboxProvider",
    "providers/podman.ts",
    2,
  ],
  [
    "sandboxProvider.local",
    "LocalOptions",
    "providers/local.types.ts",
    "createLocalSandboxProvider",
    "providers/local.ts",
    2,
  ],
  [
    "sandboxProvider.vercel",
    "VercelOptions",
    "providers/vercel.types.ts",
    "createVercelSandboxProvider",
    "providers/vercel.ts",
    2,
  ],
  [
    "sandboxProvider.daytona",
    "DaytonaOptions",
    "providers/daytona.types.ts",
    "createDaytonaSandboxProvider",
    "providers/daytona.ts",
    2,
  ],
  [
    "sandboxProvider.firecracker",
    "FirecrackerOptions",
    "providers/firecracker.types.ts",
    "createFirecrackerSandboxProvider",
    "providers/firecracker.ts",
    2,
  ],
  [
    "profile.portable",
    "AgentProfileOptions",
    "domain/agent-profile.types.ts",
    "defineAgentProfile",
    "domain/agent-profile.ts",
    2,
  ],
  [
    "secretSource.vault",
    "VaultSecretSourceOptions",
    "adapters/secrets/vault.types.ts",
    "createVaultSecretSource",
    "adapters/secrets/vault.ts",
    2,
  ],
  [
    "secretSource.aws",
    "AwsSecretSourceOptions",
    "adapters/secrets/aws.types.ts",
    "createAwsSecretSource",
    "adapters/secrets/aws.ts",
    2,
  ],
  [
    "secretSource.azure",
    "AzureSecretSourceOptions",
    "adapters/secrets/azure.types.ts",
    "createAzureSecretSource",
    "adapters/secrets/azure.ts",
    2,
  ],
  [
    "secretSource.gcp",
    "GcpSecretSourceOptions",
    "adapters/secrets/gcp.types.ts",
    "createGcpSecretSource",
    "adapters/secrets/gcp.ts",
    2,
  ],
  [
    "secretSource.onepassword",
    "OnePasswordSecretSourceOptions",
    "adapters/secrets/onepassword.types.ts",
    "createOnePasswordSecretSource",
    "adapters/secrets/onepassword.ts",
    2,
  ],
  [
    "secretSource.infisical",
    "InfisicalSecretSourceOptions",
    "adapters/secrets/infisical.types.ts",
    "createInfisicalSecretSource",
    "adapters/secrets/infisical.ts",
    2,
  ],
  [
    "sandbox.options",
    "SandboxOptions",
    "application/outpost.types.ts",
    null,
    null,
    2,
  ],
  [
    "harness.codex",
    "CodexSettings",
    "adapters/agents/settings.types.ts",
    "createCodexHarness",
    "adapters/agents/codex/codex-adapter.ts",
    2,
  ],
  [
    "harness.claude",
    "ClaudeSettings",
    "adapters/agents/settings.types.ts",
    "createClaudeHarness",
    "adapters/agents/claude/claude-adapter.ts",
    2,
  ],
  [
    "harness.agy",
    "AntigravitySettings",
    "adapters/agents/antigravity/antigravity.types.ts",
    "createAntigravityHarness",
    "adapters/agents/antigravity/antigravity-adapter.ts",
    2,
  ],
  [
    "harness.copilot",
    "CopilotSettings",
    "adapters/agents/copilot/copilot.types.ts",
    "createCopilotHarness",
    "adapters/agents/copilot/copilot-adapter.ts",
    2,
  ],
  [
    "harness.kimi",
    "KimiSettings",
    "adapters/agents/kimi/kimi.types.ts",
    "createKimiHarness",
    "adapters/agents/kimi/kimi-adapter.ts",
    2,
  ],
  [
    "agent.composed",
    "AgentOptions",
    "domain/agent.types.ts",
    "createAgent",
    "domain/agent.ts",
    2,
  ],
  [
    "transport.local",
    "LocalTransportOptions",
    "infrastructure/local-transport.types.ts",
    "createLocalTransport",
    "infrastructure/local-transport.ts",
    2,
  ],
] as const;

export const nativeRecipeKinds: Readonly<Record<string, string>> = {
  Agent: "agent",
  CliAgent: "agent",
  CustomAgent: "agent",
  DispatchAgent: "agent",
  SandboxProvider: "sandboxProvider",
  Sandbox: "sandbox",
  Workspace: "workspace",
  AgentProfile: "profile",
  ObservationHub: "observation",
  ObservationSink: "sink",
  CliHarness: "harness",
  Harness: "harness",
  ModelProvider: "modelProvider",
  DecisionProvider: "decisionProvider",
  HarnessInstructions: "instructions",
  HarnessTool: "tool",
  HarnessToolset: "toolset",
  HarnessHook: "hook",
  HarnessSkill: "skill",
  HarnessPermissions: "permissions",
  HarnessContextStrategy: "context",
  ConversationStore: "conversations",
  HarnessModelRouting: "routing",
  SecretSource: "secretSource",
  Transport: "transport",
  AbortSignal: "signal",
  Readable: "object",
  Writable: "object",
};

export const nativeRecipePaths: Readonly<Record<string, readonly string[]>> = {
  "sandbox.options": ["repository", "copies.*", "conversationHome"],
  "sandboxProvider.docker": ["volumes.*.source"],
  "sandboxProvider.podman": ["volumes.*.source"],
  "sandboxProvider.firecracker": [
    "kernel",
    "rootfs",
    "ssh.identity",
    "ssh.knownHosts",
    "jailer.directory",
  ],
  "harness.codex": ["authentication.account.file"],
  "harness.claude": ["authentication.account.file"],
  "harness.agy": ["authentication.account.file"],
  "harness.copilot": ["authentication.account.file"],
  "harness.kimi": ["authentication.account.file"],
  "transport.local": ["directory"],
};

export const nativeRecipeSecrets: Readonly<Record<string, readonly string[]>> =
  {
    "secretSource.vault": ["token"],
    "sandboxProvider.daytona": ["connection.apiKey", "connection.jwtToken"],
    "sandboxProvider.vercel": [
      "create.token",
      "create.source.password",
      "create.source.username",
    ],
    "harness.codex": ["authentication.account.key", "authentication.usage.key"],
    "harness.claude": [
      "authentication.account.key",
      "authentication.usage.key",
    ],
    "harness.agy": ["authentication.account.key", "authentication.usage.key"],
    "harness.copilot": [
      "authentication.account.key",
      "authentication.usage.key",
    ],
    "harness.kimi": ["authentication.account.key", "authentication.usage.key"],
  };
