export const dispatchFields = [
  "workspaceInfo",
  "fileOutputs",
  "text",
  "turns",
  "usage",
  "conversation",
  "value",
  "completed",
  "completion",
  "branch",
  "directory",
  "commits",
  "transcript",
  "transcriptReference",
  "logReference",
  "retainedDirectory",
  "fallback",
] as const;
