import type { ModelProvider } from "@elie-laloum/outpost";

export function createDemoModel(): ModelProvider {
  const commands = [
    "printf 'Deliberate failed check\\n' >&2; exit 7",
    "printf '\\nReport generated by Outpost.\\n' >> README.md && git add README.md && git commit -m 'Document run report'",
  ];
  let index = 0;
  return {
    name: "offline-report-demo",
    async request() {
      const command = commands[index++];
      const usage = { input: 100, cached: 20, output: 30 };
      if (!command)
        return {
          text: "Updated the README after investigating the deliberately failed check. <outpost>done</outpost>",
          usage,
        };
      return {
        text: "",
        usage,
        content: [
          {
            type: "tool-call",
            id: `command-${index}`,
            name: "shell",
            input: { command },
          },
        ],
      };
    },
  };
}
