export const recipeScalarSchemas = {
  text: { type: "string", pattern: "\\S" },
  string: { type: "string" },
  boolean: { type: "boolean" },
  integer: { type: "integer", minimum: 1, maximum: Number.MAX_SAFE_INTEGER },
  number: { type: "number" },
  object: { type: "object" },
  strings: { type: "array", items: { type: "string" } },
  reference: {
    type: "object",
    required: ["$ref"],
    properties: { $ref: { type: "string", pattern: "\\S" } },
    additionalProperties: false,
  },
} as const;

export const recipeFamilies: Readonly<Record<string, string>> = {
  agents: "agent",
  speculations: "speculationOptions",
  isolatedTasks: "isolatedOptions",
  sandboxProviders: "sandboxProvider",
  observations: "observation",
  sinks: "sink",
  profiles: "profile",
  harnesses: "harness",
  models: "modelProvider",
  transports: "transport",
  stores: "checkpointStore",
  caches: "taskCacheStore",
  artifactStores: "artifactStore",
  secrets: "secretSource",
  variables: "variables",
  tools: "tool",
  toolsets: "toolset",
  permissions: "permissions",
  hooks: "hook",
  skills: "skill",
  contexts: "context",
  instructions: "instructions",
  conversations: "conversations",
  responses: "response",
  decisions: "decisionProvider",
  questions: "decision",
  routings: "routing",
  subagents: "tool",
  queues: "queue",
  jobs: "job",
  crons: "cron",
  schedules: "schedule",
  triggers: "triggerSource",
  routes: "triggerMapper",
  resolvers: "resolver",
  verifiers: "verifier",
  guards: "guard",
  artifacts: "artifact",
  services: "service",
  functions: "callback",
  steerings: "steering",
};
